//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExzamenAnikiew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdAnikiewEntities : DbContext
    {
        public static BdAnikiewEntities _context;
        public BdAnikiewEntities()
            : base("name=BdAnikiewEntities")
        {
        }

        public static BdAnikiewEntities GetContext()
        {
            if (_context == null)
                _context = new BdAnikiewEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NomerKategorii> NomerKategorii { get; set; }
        public virtual DbSet<NomerPostavshika> NomerPostavshika { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
