//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExzamenAnikiew
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomerKategorii
    {
        public int NomerKategorii1 { get; set; }
        public string Kategoria { get; set; }
    }
}
