//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExzamenAnikiew
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Nomer { get; set; }
        public string Familia { get; set; }
        public string ImuOtchestvo { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
        public Nullable<int> Roli { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
